spring:
  profiles:
    active: "production"

  application:
    name: "kurora"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kurora_data
    username: kurora_data
    password: kurora_data

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none # required for liquibase migrations

  liquibase:
    change-log: db/changelog/db.changelog-main.xml

  main:
    banner-mode: off

server:
  port: 9595